#!/usr/bin/env python3
"""
gen_dpcm.py - extract NES DPCM samples and decode them for the Genesis ROM.

The recorder does not log sample audio, because sample audio is not
performance -- it is ROM content. $4012/$4013 point at it: a sample lives at
0xC000 + 64*addr and runs 16*len + 1 bytes. This tool pulls those bytes out of
the .nes file, decodes the DMC's 1-bit delta stream (7-bit counter, +/-2 per
bit, clocked by the $4010 rate table), resamples to the Genesis driver's V2D
loop rate, and emits a C header bank keyed by (addr, len) so the ROM can match
triggers straight from the log.

Usage:
  gen_dpcm.py game.nes capture.txt -o dpcmbank.h    # extract what the log uses
  gen_dpcm.py --selftest -o pcmsample.h             # DMC-encode the built-in
                                                    # kick, decode it back, and
                                                    # emit it as the test sample
"""
import math, sys

OUT_RATE = 20455.0                      # V2D loop rate; recorder must agree
NES_CLK = 1789773.0
# NTSC $4010 rate table: CPU cycles per delta bit
RATE_CYC = [428, 380, 340, 320, 286, 254, 226, 214, 190, 160, 142, 128, 106, 84, 72, 54]


def dmc_decode(data, rate_idx, start_level=0x40):
    """1-bit deltas -> 7-bit PCM at the DMC bit rate."""
    lvl, out = start_level, []
    for byte in data:
        for bit in range(8):            # LSB first
            if (byte >> bit) & 1:
                if lvl <= 125: lvl += 2
            else:
                if lvl >= 2: lvl -= 2
            out.append(lvl)
    return out, NES_CLK / RATE_CYC[rate_idx & 15]


def dmc_encode(samples, rate_idx):
    """PCM (0..127) -> 1-bit deltas, for the self test only."""
    lvl, bits = 0x40, []
    for s in samples:
        if s > lvl and lvl <= 125: lvl += 2; bits.append(1)
        elif lvl >= 2:             lvl -= 2; bits.append(0)
        else:                      bits.append(1)
    while len(bits) % 8: bits.append(0)
    return bytes(sum(b << i for i, b in enumerate(bits[o:o+8])) for o in range(0, len(bits), 8))


def resample(pcm, src_rate):
    n = int(len(pcm) * OUT_RATE / src_rate)
    out = []
    for i in range(n):
        x = i * src_rate / OUT_RATE
        j = int(x); f = x - j
        a = pcm[min(j, len(pcm)-1)]; b = pcm[min(j+1, len(pcm)-1)]
        v = a + (b - a) * f
        out.append(max(0, min(255, int(round(v * 2)))))   # 7-bit -> 8-bit
    return out


def kick():
    sr = OUT_RATE; n = int(sr * 0.38); out = []; ph = 0.0
    for i in range(n):
        t = i / sr
        f = 42 + 118 * math.exp(-t * 18)
        ph += 2 * math.pi * f / sr
        v = 0.85 * math.exp(-t * 9) * math.sin(ph)
        v += 0.3 * math.exp(-t * 400) * (1 if (i % 7) < 3 else -1)
        out.append(max(0, min(127, 64 + int(round(v * 60)))))
    return out


def emit(path, entries, note):
    with open(path, "w") as w:
        w.write("/* Generated by tools/gen_dpcm.py -- %s. Do not edit. */\n" % note)
        if len(entries) == 1 and entries[0][0] is None:
            pcm = entries[0][2]
            w.write("#define PCM_TEST_LEN %d\n" % len(pcm))
            w.write("static const u8 pcmTest[%d] = {\n" % len(pcm))
            for i in range(0, len(pcm), 16):
                w.write("    " + ",".join(map(str, pcm[i:i+16])) + ",\n")
            w.write("};\n")
            return
        w.write("#define DPCM_BANK_COUNT %d\n" % len(entries))
        w.write("typedef struct { u8 addr, len; u32 off, size; } DpcmEntry;\n")
        w.write("static const DpcmEntry dpcmBank[%d] = {\n" % len(entries))
        off = 0
        for (a, l), rate, pcm in entries:
            w.write("    { %d, %d, %du, %du },\n" % (a, l, off, len(pcm)))
            off += len(pcm)
        w.write("};\n")
        w.write("static const u8 dpcmData[%d] = {\n" % off)
        for _, _, pcm in entries:
            for i in range(0, len(pcm), 16):
                w.write("    " + ",".join(map(str, pcm[i:i+16])) + ",\n")
        w.write("};\n")


def main():
    out = sys.argv[sys.argv.index("-o") + 1] if "-o" in sys.argv else "dpcmbank.h"

    if "--pick" in sys.argv:
        # Extract one specific (addr, len, rate) triple found by other means --
        # typically a static scan of the game's code for the LDA#/STA $4012
        # idiom (or, as here, a table-driven trigger the scan can't decode on
        # its own: many commercial games index a shared trigger routine by a
        # per-effect table rather than hardcoding each sample inline).
        i = sys.argv.index("--pick")
        nes, addr, length, rate = sys.argv[i+1], int(sys.argv[i+2]), int(sys.argv[i+3]), int(sys.argv[i+4])
        rom = open(nes, "rb").read()
        prg_start = 16 + (512 if rom[6] & 4 else 0)
        prg_data = rom[prg_start:prg_start + rom[4] * 16384]
        prg_size = len(prg_data)
        def dmc_addr_to_offset(cpu):
            if prg_size <= 16384: return (cpu - 0xC000) % prg_size
            return (prg_size - 16384) + (cpu - 0xC000)
        cpu = 0xC000 + addr * 64
        off = dmc_addr_to_offset(cpu)
        raw = prg_data[off:off + length * 16 + 1]
        dec, bit_rate = dmc_decode(raw, rate)
        pcm = resample(dec, bit_rate)
        print("picked addr=%d len=%d rate=%d: %d DMC bytes -> %d PCM bytes"
              % (addr, length, rate, len(raw), len(pcm)))
        emit(out, [(None, rate, pcm)], "picked from %s, addr=%d len=%d rate=%d" % (nes, addr, length, rate))
        return

    if "--selftest" in sys.argv:
        src = kick()
        rate_idx = 15                               # 33.1 kHz, the DMC's finest
        enc = dmc_encode(
            resample7(src, OUT_RATE, NES_CLK / RATE_CYC[rate_idx]), rate_idx)
        dec, bit_rate = dmc_decode(enc, rate_idx)
        pcm = resample(dec, bit_rate)
        n = min(len(pcm), len(src))
        err = sum((pcm[i] - src[i] * 2) ** 2 for i in range(n)) / n
        sig = sum((s * 2 - 128) ** 2 for s in src) / len(src)
        print("selftest: %d DMC bytes -> %d PCM bytes, round-trip SNR %.1f dB"
              % (len(enc), len(pcm), 10 * math.log10(sig / max(err, 1e-9))))
        emit(out, [(None, rate_idx, pcm)], "DMC round-trip self test (kick drum)")
        return

    nes, cap = sys.argv[1], sys.argv[2]
    rom = open(nes, "rb").read()
    if rom[:4] == b"NES\x1a":
        prg = 16 + (512 if rom[6] & 4 else 0)
        prg_size = rom[4] * 16384
        prg_data = rom[prg:prg + prg_size]
    else:
        prg_data = rom

    # The DMC's CPU address window is hardware-fixed at $C000-$FFFF (256 addr
    # steps * 64 = exactly 16 KB). For any mapper that switches banks only at
    # $8000-$BFFF -- NROM, UNROM/mapper 2, CNROM/mapper 3, and most others --
    # that window is wired to the LAST 16 KB bank of the PRG image specifically
    # so a DMC sample stays reachable no matter which bank is switched in. This
    # also degenerates correctly for plain 16/32 KB NROM, where there is no
    # switching at all: the "last bank" is just the tail of the one contiguous
    # image. It does NOT hold for a mapper that can move what's fixed at $C000
    # (some MMC1/MMC3 configurations) -- those need per-game bank tracking this
    # tool does not attempt.
    prg_size = len(prg_data)
    def dmc_addr_to_offset(cpu):
        if prg_size <= 16384:
            return (cpu - 0xC000) % prg_size
        return (prg_size - 16384) + (cpu - 0xC000)

    from collections import Counter
    hits = Counter()
    trig = {}
    for line in open(cap):
        f = line.strip().split("|")[0].split(",")
        if len(f) < 26 or not f[0].lstrip("-").isdigit():
            continue
        v = [int(x) for x in f]
        if v[22]:                                   # dpcm trigger this frame
            key = (v[23], v[24])
            hits[key] += 1
            trig[key] = v[25] & 15
    if not hits:
        # fall back: frames where the channel is enabled, using the sampled regs
        for line in open(cap):
            f = line.strip().split("|")[0].split(",")
            if len(f) < 22: continue
            v = [int(x) for x in f]
            if len(v) >= 22 and v[20]:
                key = (v[16], v[17])
                hits[key] += 1
                trig[key] = v[15] & 15
    if not hits:
        print("no DPCM triggers found in %s" % cap)
        return

    print("distinct DMC triggers seen:")
    for key, n in hits.most_common():
        print("  addr=%d len=%d rate=%d : %d frames" % (key[0], key[1], trig[key], n))

    # The ROM only knows how to play one embedded sample (the C-button test
    # slot). Pick the most-triggered one -- almost always the recurring SFX
    # (footstep, hit, pickup) rather than a one-off -- and emit it in that
    # same pcmTest format the ROM already consumes, no ROM change needed.
    (a, l), n = hits.most_common(1)[0]
    r = trig[(a, l)]
    cpu = 0xC000 + a * 64
    off = dmc_addr_to_offset(cpu)
    raw = prg_data[off:off + l * 16 + 1]
    dec, bit_rate = dmc_decode(raw, r)
    pcm = resample(dec, bit_rate)
    print("selected addr=%d len=%d rate=%d (%d frames): %d DMC bytes -> %d PCM bytes"
          % (a, l, r, n, len(raw), len(pcm)))
    emit(out, [(None, r, pcm)], "extracted from %s, addr=%d len=%d rate=%d" % (nes, a, l, r))


def resample7(pcm, src, dst):
    n = int(len(pcm) * dst / src)
    out = []
    for i in range(n):
        x = i * src / dst; j = int(x); f = x - j
        a = pcm[min(j, len(pcm)-1)]; b = pcm[min(j+1, len(pcm)-1)]
        out.append(a + (b - a) * f)
    return out


if __name__ == "__main__":
    main()
