#!/usr/bin/env python3
"""
gen_dpcm.py - extract NES DPCM samples and decode them for the Genesis ROM.

The recorder does not log sample audio, because sample audio is not
performance -- it is ROM content. $4012/$4013 point at it: a sample lives at
0xC000 + 64*addr and runs 16*len + 1 bytes. This tool pulls those bytes out of
the .nes file, decodes the DMC's 1-bit delta stream (7-bit counter, +/-2 per
bit, clocked by the $4010 rate table), resamples to the Genesis driver's V2D
loop rate, and emits a C header bank keyed by (addr, len) so the ROM can match
triggers straight from the log.

Usage:
  gen_dpcm.py game.nes capture.txt -o dpcmbank.h    # extract what the log uses
  gen_dpcm.py --selftest -o pcmsample.h             # DMC-encode the built-in
                                                    # kick, decode it back, and
                                                    # emit it as the test sample
"""
import math, sys

OUT_RATE = 20455.0                      # V2D loop rate; recorder must agree
NES_CLK = 1789773.0
# NTSC $4010 rate table: CPU cycles per delta bit
RATE_CYC = [428, 380, 340, 320, 286, 254, 226, 214, 190, 160, 142, 128, 106, 84, 72, 54]


def dmc_decode(data, rate_idx, start_level=0x40):
    """1-bit deltas -> 7-bit PCM at the DMC bit rate."""
    lvl, out = start_level, []
    for byte in data:
        for bit in range(8):            # LSB first
            if (byte >> bit) & 1:
                if lvl <= 125: lvl += 2
            else:
                if lvl >= 2: lvl -= 2
            out.append(lvl)
    return out, NES_CLK / RATE_CYC[rate_idx & 15]


def dmc_encode(samples, rate_idx):
    """PCM (0..127) -> 1-bit deltas, for the self test only."""
    lvl, bits = 0x40, []
    for s in samples:
        if s > lvl and lvl <= 125: lvl += 2; bits.append(1)
        elif lvl >= 2:             lvl -= 2; bits.append(0)
        else:                      bits.append(1)
    while len(bits) % 8: bits.append(0)
    return bytes(sum(b << i for i, b in enumerate(bits[o:o+8])) for o in range(0, len(bits), 8))


def resample(pcm, src_rate):
    n = int(len(pcm) * OUT_RATE / src_rate)
    out = []
    for i in range(n):
        x = i * src_rate / OUT_RATE
        j = int(x); f = x - j
        a = pcm[min(j, len(pcm)-1)]; b = pcm[min(j+1, len(pcm)-1)]
        v = a + (b - a) * f
        out.append(max(0, min(255, int(round(v * 2)))))   # 7-bit -> 8-bit
    return out


def kick():
    sr = OUT_RATE; n = int(sr * 0.38); out = []; ph = 0.0
    for i in range(n):
        t = i / sr
        f = 42 + 118 * math.exp(-t * 18)
        ph += 2 * math.pi * f / sr
        v = 0.85 * math.exp(-t * 9) * math.sin(ph)
        v += 0.3 * math.exp(-t * 400) * (1 if (i % 7) < 3 else -1)
        out.append(max(0, min(127, 64 + int(round(v * 60)))))
    return out


def emit(path, entries, note):
    with open(path, "w") as w:
        w.write("/* Generated by tools/gen_dpcm.py -- %s. Do not edit. */\n" % note)
        if len(entries) == 1 and entries[0][0] is None:
            pcm = entries[0][2]
            w.write("#define PCM_TEST_LEN %d\n" % len(pcm))
            w.write("static const u8 pcmTest[%d] = {\n" % len(pcm))
            for i in range(0, len(pcm), 16):
                w.write("    " + ",".join(map(str, pcm[i:i+16])) + ",\n")
            w.write("};\n")
            return
        w.write("#define DPCM_BANK_COUNT %d\n" % len(entries))
        w.write("typedef struct { u8 addr, len; u32 off, size; } DpcmEntry;\n")
        w.write("static const DpcmEntry dpcmBank[%d] = {\n" % len(entries))
        off = 0
        for (a, l), rate, pcm in entries:
            w.write("    { %d, %d, %du, %du },\n" % (a, l, off, len(pcm)))
            off += len(pcm)
        w.write("};\n")
        w.write("static const u8 dpcmData[%d] = {\n" % off)
        for _, _, pcm in entries:
            for i in range(0, len(pcm), 16):
                w.write("    " + ",".join(map(str, pcm[i:i+16])) + ",\n")
        w.write("};\n")


def main():
    out = sys.argv[sys.argv.index("-o") + 1] if "-o" in sys.argv else "dpcmbank.h"

    if "--selftest" in sys.argv:
        src = kick()
        rate_idx = 15                               # 33.1 kHz, the DMC's finest
        enc = dmc_encode(
            resample7(src, OUT_RATE, NES_CLK / RATE_CYC[rate_idx]), rate_idx)
        dec, bit_rate = dmc_decode(enc, rate_idx)
        pcm = resample(dec, bit_rate)
        n = min(len(pcm), len(src))
        err = sum((pcm[i] - src[i] * 2) ** 2 for i in range(n)) / n
        sig = sum((s * 2 - 128) ** 2 for s in src) / len(src)
        print("selftest: %d DMC bytes -> %d PCM bytes, round-trip SNR %.1f dB"
              % (len(enc), len(pcm), 10 * math.log10(sig / max(err, 1e-9))))
        emit(out, [(None, rate_idx, pcm)], "DMC round-trip self test (kick drum)")
        return

    nes, cap = sys.argv[1], sys.argv[2]
    rom = open(nes, "rb").read()
    if rom[:4] == b"NES\x1a":
        prg = 16 + (512 if rom[6] & 4 else 0)
        prg_size = rom[4] * 16384
        prg_data = rom[prg:prg + prg_size]
    else:
        prg_data = rom

    used = {}
    for line in open(cap):
        f = line.strip().split("|")[0].split(",")
        if len(f) < 26 or not f[0].lstrip("-").isdigit():
            continue
        v = [int(x) for x in f]
        if v[22]:                                   # dpcm trigger this frame
            used[(v[23], v[24])] = v[25] & 15       # (addr, len) -> rate
    if not used:
        # fall back: frames where the channel is enabled, using the sampled regs
        for line in open(cap):
            f = line.strip().split("|")[0].split(",")
            if len(f) < 22: continue
            v = [int(x) for x in f]
            if len(v) >= 22 and v[20]:
                used[(v[16], v[17])] = v[15] & 15
    entries = []
    for (a, l), r in sorted(used.items()):
        cpu = 0xC000 + a * 64
        off = (cpu - 0x8000) % len(prg_data) if len(prg_data) <= 0x8000 else cpu - 0x8000
        raw = prg_data[off:off + l * 16 + 1]
        dec, bit_rate = dmc_decode(raw, r)
        entries.append(((a, l), r, resample(dec, bit_rate)))
        print("sample addr=%d len=%d rate=%d: %d bytes -> %d PCM" % (a, l, r, len(raw), len(entries[-1][2])))
    emit(out, entries, "extracted from %s" % nes)


def resample7(pcm, src, dst):
    n = int(len(pcm) * dst / src)
    out = []
    for i in range(n):
        x = i * src / dst; j = int(x); f = x - j
        a = pcm[min(j, len(pcm)-1)]; b = pcm[min(j+1, len(pcm)-1)]
        out.append(a + (b - a) * f)
    return out


if __name__ == "__main__":
    main()
