#!/usr/bin/env python3
"""
gen_apudata.py - pack nes_apu_data.txt into a C header so the ROM can play the
capture with no emulator scripting at all.

10 bytes a frame, big-endian:
  [0..1]  pulse1: period(11) | duty<<11 | on<<13
  [2]     pulse1 volume (raw register nibble, same as the v1 script path)
  [3..4]  pulse2: same layout
  [5]     pulse2 volume
  [6..7]  triangle: period(11) | on<<11
  [8]     noise: period(4) | mode<<4 | on<<5
  [9]     noise volume

Usage:  python3 tools/gen_apudata.py nes_apu_data.txt -o apudata.h
"""
import sys

src = sys.argv[1]
out = sys.argv[sys.argv.index("-o") + 1] if "-o" in sys.argv else "apudata.h"

frames = []
for line in open(src):
    line = line.strip()
    if not line or line.startswith("#"):
        continue
    v = line.split(",")[0].split("|")[0]  # tolerate v2 pcm suffix
    f = [int(x) for x in line.split("|")[0].split(",")]
    if len(f) < 14:
        continue
    p1 = (f[0] & 0x7FF) | ((f[2] & 3) << 11) | ((f[3] & 1) << 13)
    p2 = (f[4] & 0x7FF) | ((f[6] & 3) << 11) | ((f[7] & 1) << 13)
    tri = (f[8] & 0x7FF) | ((f[9] & 1) << 11)
    noi = (f[10] & 0x0F) | ((f[13] & 1) << 4) | ((f[12] & 1) << 5)
    # v2 captures carry post-envelope volumes in fields 19/20; use them if there
    p1v = (f[18] if len(f) >= 22 else f[1]) & 0x0F
    p2v = (f[19] if len(f) >= 22 else f[5]) & 0x0F
    frames.append(bytes([p1 >> 8, p1 & 0xFF, p1v,
                         p2 >> 8, p2 & 0xFF, p2v,
                         tri >> 8, tri & 0xFF,
                         noi, f[11] & 0x0F]))

blob = b"".join(frames)
with open(out, "w") as w:
    w.write("/* Generated by tools/gen_apudata.py from %s - do not edit. */\n" % src)
    w.write("#define APU_DATA_FRAMES %d\n" % len(frames))
    w.write("#define APU_DATA_STRIDE 10\n")
    w.write("static const u8 apuData[%d] = {\n" % len(blob))
    for i in range(0, len(blob), 16):
        w.write("    " + ",".join("%d" % b for b in blob[i:i+16]) + ",\n")
    w.write("};\n")
print("%d frames, %d bytes -> %s" % (len(frames), len(blob), out))
